import { ApiProperty, ApiPropertyOptional } from '@nestjs/swagger';
import { Transform } from 'class-transformer';
import {
  IsEnum,
  IsNotEmpty,
  IsNumber,
  IsOptional,
  IsString,
  IsUUID,
  Max,
  MaxLength,
  Min,
  MinLength,
  ValidateIf,
} from 'class-validator';

import { BUSINESS_RULE, SWAGGER_EXAMPLE } from '../../../common/constants';
import { PaginationQueryDto } from '../../../common/dto';
import { EntryType, LeadStatus } from '../../../common/enums';
import { emptyToUndefined, toNumber, trimString, trimToNull } from '../../../common/utils';
import { IsIsoDate } from '../../../common/validators/is-iso-date.validator';
import { LocationRefDto } from '../../locations/dto/location.dto';

export class PersonRefDto {
  @ApiProperty({ format: 'uuid' })
  id: string;

  @ApiProperty({ example: 'Ravi Kumar' })
  name: string;
}

/** One row of a lead's history: a follow-up or a manual status change. */
export class EntryDto {
  @ApiProperty({ format: 'uuid', example: SWAGGER_EXAMPLE.UUID })
  id: string;

  @ApiProperty({ format: 'uuid' })
  leadId: string;

  @ApiProperty({ format: 'uuid' })
  projectId: string;

  @ApiProperty({ enum: EntryType })
  entryType: EntryType;

  @ApiProperty({ enum: LeadStatus, description: 'The lead’s status after this entry.' })
  status: LeadStatus;

  @ApiPropertyOptional({ nullable: true, type: String })
  note: string | null;

  @ApiPropertyOptional({ nullable: true, type: String, example: SWAGGER_EXAMPLE.DATE })
  nextFollowUpDate: string | null;

  @ApiPropertyOptional({ type: LocationRefDto, nullable: true, description: 'The typed location.' })
  location: LocationRefDto | null;

  @ApiProperty({ description: 'TRUE when the entry carries a visit photo.' })
  hasPhoto: boolean;

  @ApiPropertyOptional({ nullable: true, type: String, description: 'Short-lived signed URL.' })
  photoUrl: string | null;

  @ApiPropertyOptional({ nullable: true, type: Number, example: 18.50043 })
  latitude: number | null;

  @ApiPropertyOptional({ nullable: true, type: Number, example: 73.856743 })
  longitude: number | null;

  @ApiPropertyOptional({ nullable: true, type: Number, example: 12 })
  gpsAccuracyM: number | null;

  @ApiProperty({
    description: 'Accuracy worse than 100 m — shown as "Low accuracy", never rejected.',
  })
  lowAccuracy: boolean;

  @ApiProperty({ type: PersonRefDto, description: 'Who logged it. Kept after a transfer.' })
  user: PersonRefDto;

  @ApiProperty({ description: 'Server time — the official visit time.' })
  createdAt: Date;

  @ApiProperty()
  updatedAt: Date;

  @ApiProperty({ description: 'Note or next date changed after saving.' })
  edited: boolean;

  @ApiProperty({
    description: 'The caller can still edit it: their own entry, today (IST), open project.',
  })
  editable: boolean;
}

/**
 * The visit-proof fields. Multipart sends strings, so numbers are converted
 * explicitly. Required only in a door-to-door project — the service decides.
 */
export class VisitProofFieldsDto {
  @ApiPropertyOptional({ minimum: -90, maximum: 90, example: 18.50043 })
  @IsOptional()
  @Transform(toNumber)
  @IsNumber({ allowNaN: false, allowInfinity: false })
  @Min(-90)
  @Max(90)
  latitude?: number;

  @ApiPropertyOptional({ minimum: -180, maximum: 180, example: 73.856743 })
  @IsOptional()
  @Transform(toNumber)
  @IsNumber({ allowNaN: false, allowInfinity: false })
  @Min(-180)
  @Max(180)
  longitude?: number;

  @ApiPropertyOptional({ minimum: 0, description: 'Metres, as the phone reports it.', example: 12 })
  @IsOptional()
  @Transform(toNumber)
  @IsNumber({ allowNaN: false, allowInfinity: false })
  @Min(0)
  @Max(BUSINESS_RULE.MAX_GPS_ACCURACY_METRES)
  gpsAccuracyM?: number;

  @ApiPropertyOptional({
    description: 'From POST /visits/capture-token, issued when the camera opened.',
  })
  @IsOptional()
  @Transform(emptyToUndefined)
  @IsString()
  @MaxLength(512)
  captureToken?: string;
}

export class LogFollowUpDto extends VisitProofFieldsDto {
  @ApiProperty({
    format: 'uuid',
    description:
      'One-time id generated by the form. A retry with the same id returns the first save.',
  })
  @IsUUID('4')
  clientRequestId: string;

  @ApiProperty({ enum: LeadStatus, description: 'Not New. A Converted lead stays Converted.' })
  @IsEnum(LeadStatus)
  status: LeadStatus;

  @ApiProperty({
    minLength: BUSINESS_RULE.NOTE_MIN_LENGTH,
    example: 'Met the owner; wants a demo next week.',
  })
  @Transform(trimString)
  @IsString()
  @MinLength(BUSINESS_RULE.NOTE_MIN_LENGTH)
  @MaxLength(BUSINESS_RULE.NOTE_MAX_LENGTH)
  note: string;

  @ApiPropertyOptional({
    example: SWAGGER_EXAMPLE.DATE,
    description:
      'Required for Follow-up scheduled; ignored and cleared for Not interested, Converted and Lost.',
  })
  @IsOptional()
  @Transform(emptyToUndefined)
  @IsIsoDate()
  nextFollowUpDate?: string;

  @ApiProperty({ description: 'Typed location, pre-filled with the lead’s.', example: 'Wanowrie' })
  @Transform(trimString)
  @IsString()
  @IsNotEmpty()
  @MaxLength(BUSINESS_RULE.LOCATION_MAX_LENGTH * 2)
  location: string;
}

export class ChangeStatusDto {
  @ApiProperty({ format: 'uuid', description: 'One-time id; a retry returns the first save.' })
  @IsUUID('4')
  clientRequestId: string;

  @ApiProperty({ enum: LeadStatus })
  @IsEnum(LeadStatus)
  status: LeadStatus;

  @ApiProperty({ description: 'Reason for the change.', minLength: BUSINESS_RULE.NOTE_MIN_LENGTH })
  @Transform(trimString)
  @IsString()
  @MinLength(BUSINESS_RULE.NOTE_MIN_LENGTH)
  @MaxLength(BUSINESS_RULE.NOTE_MAX_LENGTH)
  note: string;

  @ApiPropertyOptional({
    example: SWAGGER_EXAMPLE.DATE,
    description: 'Required for Follow-up scheduled.',
  })
  @IsOptional()
  @Transform(emptyToUndefined)
  @IsIsoDate()
  nextFollowUpDate?: string;
}

export class EditEntryDto {
  @ApiPropertyOptional({ minLength: BUSINESS_RULE.NOTE_MIN_LENGTH })
  @IsOptional()
  @Transform(trimString)
  @IsString()
  @MinLength(BUSINESS_RULE.NOTE_MIN_LENGTH)
  @MaxLength(BUSINESS_RULE.NOTE_MAX_LENGTH)
  note?: string;

  @ApiPropertyOptional({
    nullable: true,
    example: SWAGGER_EXAMPLE.DATE,
    description: 'Follow-ups only. Null clears it where the status allows.',
  })
  @IsOptional()
  @Transform(trimToNull)
  @ValidateIf((_, value) => value !== null)
  @IsIsoDate()
  nextFollowUpDate?: string | null;
}

export class ListEntriesQueryDto extends PaginationQueryDto {}
