/** `ConfigService` namespaces, one per `registerAs` in config/configuration.ts. */
export const CONFIG_NAMESPACE = {
  APP: 'app',
  DATABASE: 'database',
  SUPABASE: 'supabase',
  SWAGGER: 'swagger',
  VISIT: 'visit',
} as const;

export const NODE_ENVIRONMENT = {
  DEVELOPMENT: 'development',
  PRODUCTION: 'production',
  TEST: 'test',
} as const;

export type NodeEnvironment = (typeof NODE_ENVIRONMENT)[keyof typeof NODE_ENVIRONMENT];

export const CONFIG_DEFAULT = {
  PORT: 4100,
} as const;

/** Every environment variable the service reads. Nothing else touches `process.env`. */
export const ENV = {
  NODE_ENV: 'NODE_ENV',
  PORT: 'PORT',
  APP_NAME: 'APP_NAME',
  API_PREFIX: 'API_PREFIX',
  API_VERSION: 'API_VERSION',
  CORS_ORIGINS: 'CORS_ORIGINS',
  BODY_LIMIT: 'BODY_LIMIT',
  THROTTLE_TTL_SECONDS: 'THROTTLE_TTL_SECONDS',
  THROTTLE_LIMIT: 'THROTTLE_LIMIT',
  APP_URL: 'APP_URL',

  DATABASE_URL: 'DATABASE_URL',
  DIRECT_URL: 'DIRECT_URL',
  DB_HOST: 'DB_HOST',
  DB_PORT: 'DB_PORT',
  DB_USERNAME: 'DB_USERNAME',
  DB_PASSWORD: 'DB_PASSWORD',
  DB_NAME: 'DB_NAME',
  DB_SSL: 'DB_SSL',
  DB_SSL_REJECT_UNAUTHORIZED: 'DB_SSL_REJECT_UNAUTHORIZED',
  DB_POOL_MAX: 'DB_POOL_MAX',
  DB_POOL_IDLE_TIMEOUT_MS: 'DB_POOL_IDLE_TIMEOUT_MS',
  DB_CONNECTION_TIMEOUT_MS: 'DB_CONNECTION_TIMEOUT_MS',
  DB_STATEMENT_TIMEOUT_MS: 'DB_STATEMENT_TIMEOUT_MS',
  DB_LOGGING: 'DB_LOGGING',
  DB_MIGRATIONS_RUN: 'DB_MIGRATIONS_RUN',

  SUPABASE_URL: 'SUPABASE_URL',
  SUPABASE_ANON_KEY: 'SUPABASE_ANON_KEY',
  SUPABASE_SERVICE_ROLE_KEY: 'SUPABASE_SERVICE_ROLE_KEY',
  SUPABASE_JWT_SECRET: 'SUPABASE_JWT_SECRET',
  SUPABASE_STORAGE_BUCKET: 'SUPABASE_STORAGE_BUCKET',
  SUPABASE_TIMEOUT_MS: 'SUPABASE_TIMEOUT_MS',
  AUTH_REDIRECT_URL: 'AUTH_REDIRECT_URL',

  CAPTURE_TOKEN_SECRET: 'CAPTURE_TOKEN_SECRET',
  SIGNED_URL_TTL_SECONDS: 'SIGNED_URL_TTL_SECONDS',

  SWAGGER_ENABLED: 'SWAGGER_ENABLED',
  SWAGGER_PATH: 'SWAGGER_PATH',
  SWAGGER_USER: 'SWAGGER_USER',
  SWAGGER_PASSWORD: 'SWAGGER_PASSWORD',

  SEED_SUPER_ADMIN_NAME: 'SEED_SUPER_ADMIN_NAME',
  SEED_SUPER_ADMIN_EMAIL: 'SEED_SUPER_ADMIN_EMAIL',
  SEED_SUPER_ADMIN_PASSWORD: 'SEED_SUPER_ADMIN_PASSWORD',
} as const;
